services:
  backend:
    build:
      context: .
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container_credibanco:3306/${MYSQL_DATABASE}?useSSL=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JAVA_OPTS: "-XX:MaxRAM=400m -XX:+UseSerialGC -Xss256k"
    deploy:
      resources:
        limits:
          memory: 450m
    networks:
      - app-network-credibanco
    restart: unless-stopped

networks:
  app-network-credibanco:
    external: true