services:
  backend:
    build: .
    image: backend-credibanco
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JAVA_OPTS: "-XX:MaxRAM=400m -XX:+UseSerialGC -Xss256k"
    deploy:
      resources:
        limits:
          memory: 450m
    networks:
      - app-network-credibanco
    restart: unless-stopped

networks:
  app-network-credibanco:
    external: true